services:
  landing:
    build:
      context: ./mvplanding/mvp
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    restart: always

  analyzer:
    build:
      context: ./mvpAnalyzer/mvp
      dockerfile: Dockerfile
    ports:
      - "5177:80"
    restart: always

  text-analyzer:
    build:
      context: ./mvpTextAnalyzer/mvp
      dockerfile: Dockerfile
    ports:
      - "5175:80"
    restart: always
